# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x=np.random.random((3,3,3))
print(x)

[[[0.73031475 0.22419156 0.56336714]
  [0.79646071 0.7750693  0.92843534]
  [0.73619236 0.36857118 0.02395564]]

 [[0.09927787 0.76124495 0.48033217]
  [0.97264571 0.73930599 0.10641905]
  [0.18826338 0.60418302 0.90889261]]

 [[0.61748673 0.25178331 0.60594551]
  [0.69701805 0.41228034 0.41858366]
  [0.26035228 0.51707172 0.22589269]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
x=np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [2]:
x=np.ones((3,3))
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [6]:
x=np.random.random((5,5))
print("Original Array:")
print(x)
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print("After Normalization:")
print(x)

Original Array:
[[0.25698637 0.10188158 0.27470949 0.60225025 0.68874605]
 [0.53884296 0.7084333  0.22406723 0.56686158 0.66746558]
 [0.63231894 0.57425819 0.69950151 0.43056825 0.78980572]
 [0.01260935 0.15033079 0.70570798 0.31838443 0.59273818]
 [0.62217397 0.58507696 0.82639058 0.4850681  0.5191318 ]]
After Normalization:
[[0.30029818 0.10970052 0.3220769  0.7245693  0.83085806]
 [0.64665243 0.85505038 0.25984609 0.68108259 0.80470796]
 [0.76151866 0.69017178 0.84407471 0.51360105 0.95504337]
 [0.         0.16923644 0.85170142 0.37574604 0.71288057]
 [0.74905219 0.70346622 1.         0.58057218 0.62243073]]


# 5.  How to find common values between two arrays?

In [9]:
array1=np.array([11,12,13,14,15,16])
print("Array1:",array1)
array2=[11,19,18,17,16,15]
print("Array2:",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1,array2))

Array1: [11 12 13 14 15 16]
Array2: [11, 19, 18, 17, 16, 15]
Common values between two arrays:
[11 15 16]


# 6.How to get the dates of yesterday, today and tomorrow?

In [11]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [15]:
x=np.random.random((3,3))
print("Array1:",x)
y=np.random.random((3,3))
print("Array2:",y)
print("Two arrays are equal or not?")
equal_not=np.allclose(x,y)
print(equal_not)

Array1: [[0.4470127  0.33339381 0.97659401]
 [0.40476942 0.57377811 0.82929141]
 [0.97694651 0.83182522 0.31596527]]
Array2: [[0.69598062 0.80065152 0.1758615 ]
 [0.2033165  0.26565826 0.86994145]
 [0.33368275 0.22921046 0.59290004]]
Two arrays are equal or not?
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [16]:
x=np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()]=0
print("Maximum value replaced by 0:",x)

Original array:
[0.55262231 0.47416006 0.78685353 0.04049558 0.76396052 0.56661489
 0.08661492 0.37466236 0.63361509 0.20466134]
Maximum value replaced by 0: [0.55262231 0.47416006 0.         0.04049558 0.76396052 0.56661489
 0.08661492 0.37466236 0.63361509 0.20466134]


# 9. How to print all the values of an array?

In [18]:
array=np.arange(30)
np.set_printoptions(threshold=np.inf)
print("All values of an array",array)

All values of an array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


# 10.Subtract the mean of each row of a matrix

In [21]:
import numpy as np
print("Original matrix:\n")
x = np.random.rand(2, 4)
print(x)
print("\nSubtract the mean of each row of the said matrix:\n")
y = x - x.mean(axis=1, keepdims=True)
print(y)

Original matrix:

[[0.32428068 0.7267192  0.62553951 0.76604154]
 [0.16988802 0.05577882 0.87597179 0.46490381]]

Subtract the mean of each row of the said matrix:

[[-0.28636455  0.11607397  0.01489428  0.1553963 ]
 [-0.22174759 -0.33585679  0.48433618  0.0732682 ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [25]:
x=np.ones(10)
y=np.random.randint(0,len(x),20)
x += np.bincount(y,minlength=len(x))
print(x)

[2. 3. 1. 4. 2. 3. 3. 5. 3. 4.]


# 12.How to get the diagonal of a dot product?

In [27]:
x=np.random.uniform(0,1,(5,5))
y=np.random.uniform(0,1,(5,5))
np.diag(np.dot(x,y))

array([0.78432798, 1.04983786, 1.44906627, 0.59608669, 0.90968937])

# 13.How to find the most frequent value in an array?

In [28]:
x=np.random.randint(0,3,6)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[2 2 2 0 2 2]
Most frequent value in the above array:
2


# 14.How to get the n largest values of an array

In [29]:
x=np.arange(15)
print("Original array:")
print(x)
np.random.shuffle(x)
n=1
print(x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14]


# 15.How to create a record array from a regular array?

In [30]:
import numpy as np
arra1 = np.array([("ABC", 88.5, 90),("XYZ", 87, 99),("PQR", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['ABC' '88.5' '90']
 ['XYZ' '87' '99']
 ['PQR' '85.5' '91']]

Record array;
[(b'ABC', 88.5, 90) (b'XYZ', 87. , 99) (b'PQR', 85.5, 91)]
